companieshouse/api-sdk-node

Makefile
Fix build artifact name in makefile to match repo name required by concourse task.
=> Fix build artifact name

src/client.ts, src/services/company-psc/service.ts, src/services/order/mid/mapping.ts, src/services/order/mid/service.ts, src/services/payment/service.ts, test/services/company-psc/service.spec.ts, test/services/mid/service.spec.ts, test/services/payment/service.spec.ts
There were various errors with the linting so i ran `npm run lint:fix` to fix them
=> fix linting errors

src/client.ts
=> OBJ-392 Client required updates

Makefile
add security-check to check for vulnerabilities
=> add npm audit

.npmrc
add .npmrc file with moderate audit level
=> add suppression level

src/services/order/order/mapping.ts, src/services/order/order/types.ts
Added fields for CertificateItemOptions director details.
Jira Ticket : BI6016
=> Added more fields for DirectorDetails

src/services/order/order/types.ts
Added DirectorDetails type
Jira Ticket BI-6016
=> Added DirectorDetails type

src/services/order/certificates/types.ts
- Add code missing from `api-sdk-node` 
- Add additional null values
=> Move code from ch-sdk-node and add additional null values

src/services/order/order/mapping.ts, src/services/order/order/types.ts
Added options to secretary
Jira Ticket BI-6221
=> Added options to secretary

src/client.ts, src/http/http-client.ts, src/http/request-client.ts, src/services/search/alphabetical-search/index.ts, src/services/search/alphabetical-search/service.ts, src/services/search/alphabetical-search/types.ts, test/http/http-client.spec.ts, test/services/search/alphabetical-search/service.spec.ts
Added alphabetical search service POST functionality to allow requests to the search API
Resolves: BI-6633
=> add search service

src/http/http-client.ts, src/http/request-client.ts, src/services/search/alphabetical-search/service.ts, src/services/search/alphabetical-search/types.ts, test/http/http-client.spec.ts, test/services/search/alphabetical-search/service.spec.ts
=> Update SDK to use GET method instead of POST

src/services/search/dissolved-search/types.ts, test/services/search/dissolved-search/service.spec.ts
=> update dissolved search model to align with spec update test

src/services/search/dissolved-search/service.ts
Change search types names to be consistent with api spec
Resolves: BI-7513
=> update names to reflect api spec

src/services/search/alphabetical-search/types.ts, test/services/search/alphabetical-search/service.spec.ts
=> add ordered alpha key field to alpha search update test

package-lock.json
=> chore: ran npm audit -fix

src/client.ts
https://companieshouse.atlassian.net/browse/FAML-746
=> feature: added new services to client

src/services/search/alphabetical-search/types.ts, src/services/search/dissolved-search/service.ts, test/services/search/alphabetical-search/service.spec.ts
match alpha search model to spec 
update test 
set start index to url for dissolved search api call
Resolves: BI-7008
=> Refactor to match search model specs

src/client.ts
Fix spelling of PSCDiscrepanciesReportService import.
=> fix spelling of psc-discrepancies in client.ts

package-lock.json, package.json, src/services/search/dissolved-search/types.ts, test/services/search/dissolved-search/service.spec.ts
=> Update sdk dissolved models to use registered office address

src/services/psc-discrepancies/types.ts, test/services/psc-discrepancies/service.spec.ts
=> Add psc_type to types.ts 

package-lock.json, package.json, src/client.ts, src/services/search/enhanced-search/index.ts, src/services/search/enhanced-search/service.ts, src/services/search/enhanced-search/types.ts, test/services/search/enhanced-search/service.spec.ts
Add enhanced search api call to sdk with the optional query params:
company name, location and incorporated to and from dates.
Resolves: BI-8655
=> add enhanced search api call

src/services/transaction/service.ts, test/services/transaction/service.spec.ts
Put function added if there is no id there is no point contiuing do if that check fails we should just return an  http 400 error.
=> NCS-642 Added a put function for transactions

src/services/order/certificates/mapping.ts, src/services/order/certificates/types.ts, test/services/certificates/service.spec.ts
* Company type field will be attached by Certificate orders API.
=> BI-8867 Remove company_type field from request model

src/services/confirmation-statement/service.ts, src/services/confirmation-statement/types.ts, test/services/confirmation-statement/confirmation.statement.mock.ts, test/services/confirmation-statement/confirmation.statement.spec.ts
Moved from the private-api-sdk-node
=> NCS-674 Added save trading status

src/services/confirmation-statement/service.ts, src/services/confirmation-statement/types.ts, test/services/confirmation-statement/confirmation.statement.mock.ts, test/services/confirmation-statement/confirmation.statement.spec.ts
[NCS-689](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-689)
Change trading status model to use boolean field instead of section status.
=> NCS-689 Amend trading status model

src/services/order/certificates/mapping.ts, src/services/order/certificates/types.ts, src/services/order/order/mapping.ts, src/services/order/order/types.ts, test/services/certificates/service.spec.ts, test/services/order/service.spec.ts
- Change to correct wording from principle to principal
=> BI-9041 Change to use correct word for certificate item options

src/services/order/order/mapping.ts, test/services/order/service.spec.ts
Resolves [BI-9121](https://companieshouse.atlassian.net/browse/BI-9121)
=> BI-9121 Add spaces between braces for proper code formatting

src/services/order/checkout/index.ts, src/services/order/checkout/mapping.ts, src/services/order/checkout/service.ts, src/services/order/checkout/types.ts, test/services/checkout/service.spec.ts
=> BI-6864 - Add get checkout to sdk

src/client.ts, src/services/order/checkout/service.ts, src/services/order/index.ts
Fix issue where the reference to call getCheckout was not available.
=> Add reference to enable calling of the getCheckout method in web app

src/services/order/certificates/mapping.ts, src/services/order/certificates/types.ts
- Add company type to certificate item request
[BI-9019: Feature Flags for LLP/LP journeys](https://companieshouse.atlassian.net/browse/BI-9193)
=> BI-9193 Add company type to certificate item request

src/services/search/advanced-search/service.ts
Update endpoint to advanced search from enhanced to enable web to use latest api changes.
Resolves: GCI-1947
=> GCI-1947 - Update endpoint to advanced search from enhanced

src/services/search/advanced-search/service.ts, test/services/search/advanced-search/service.spec.ts
add size param to advanced search url builder update tests
=> add size param to advanced search url builder update tests

src/services/confirmation-statement/service.ts, test/services/confirmation-statement/confirmation.statement.mock.ts, test/services/confirmation-statement/confirmation.statement.spec.ts
implement multiple officers call
=> BI-9487 - implement multiple officers

package-lock.json, package.json, src/services/order/certificates/service.ts
* Fix test failures in certificates webapp
=> Re-add cert service functions back to prototype

src/services/order/certificates/service.ts, test/services/certificates/service.spec.ts
* Return Result object representing status of create initial certificate
operation.
Related:
[BI-9890](https://companieshouse.atlassian.net/browse/BI-9890)
=> Change certs initial request to return status

package-lock.json, src/services/order/certificates/types.ts, src/services/order/checkout/mapping.ts, src/services/order/checkout/types.ts, src/services/order/order/mapping.ts, src/services/order/order/types.ts, test/services/certificates/service.spec.ts, test/services/checkout/service.spec.ts, test/services/order/service.spec.ts
- Add administrators details field to resources
Relates to: [BI-9851 Update api sdk node](https://companieshouse.atlassian.net/browse/BI-9851)
=> BI-9851 Add administrators details field to resource

test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Change status code response for overseas entities
Part of [ROE-152](https://companieshouse.atlassian.net/browse/ROE-152)
=> Change status code response for overseas entities

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
https://companieshouse.atlassian.net/browse/ROE-278
Updated model with:
beneficial owners statement
beneficial owners individual
beneficial owners corporate
beneficial owners government or public authority
=> Roe 278 send roe bo data

src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
Update date model and fix nature_of_control_types on individual BO
Part of [ROE-319](https://companieshouse.atlassian.net/browse/ROE-319)
=> Update date model and fix nature_of_control_types on individual BO

src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
Updating BeneficialOwnerGovernmentOrPublicAuthority to have an array of NatureOfControls rather than singulars
=> ROE-298 Updating Overseas Entities model to have array of NOCs

src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
https://companieshouse.atlassian.net/browse/ROE-399
Updated roe Entity model with: is_on_register_in_country_formed_in
=> ROE-399 Update roe entity model

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Related [ROE-409](https://companieshouse.atlassian.net/browse/ROE-409)
- Add MO corporate model and mapping to OE
=> Add MO corporate model and mapping to OE

src/client.ts, src/services/order/search/index.ts, src/services/order/search/service.ts, src/services/order/search/types.ts, test/services/order/search.spec.ts
* Endpoint of orders search service has changed.
=> GCI-2137 Rework orders search service into checkout search

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Jira: https://companieshouse.atlassian.net/browse/ROE-916
Updated sdk model to include due diligence.
=> ROE-916 Add Overseas entity  due diligence data to the node sdk model

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
https://companieshouse.atlassian.net/browse/ROE-967
Mapping for date from InputDate object to an iso string needs to be completed to work with the api.
=> ROE-967 Due diligence date has to be mapped to a string

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
* INDIVIDUALS and CORPORATES need to be plural
* The spreadsheet outputs a "Yes" or "No" string which needs to be converted to a boolean
=> Update trust fields to match spreadsheet output

src/services/order/basket/service.ts, src/services/order/basket/types.ts, test/services/basket/service.spec.ts
- Implement service methods to call orders api basket endpoints:
- Remove basket item
- Get basket links
- Add basket types for sdk users
[GCI-2158](https://companieshouse.atlassian.net/browse/GCI-2158)
=> GCI-2158 Implement basket endpoints

package-lock.json, src/services/order/basket/service.ts, test/services/basket/service.spec.ts, test/stubs/item.stub.ts
* Move code from post item to basket into a new private method
* Reuse the above private method for new handler
* Add new folder for stub objects
=> GCI-2207 Add new handler for append to basket endpoint

src/services/order/certified-copies/service.ts, src/services/order/certified-copies/types.ts
Pathing certified documents implementation added
BI-11573
=> Cert docs patching

src/services/order/certified-copies/types.ts
Amended item definition reference for CertifiedCopyItem item options
BI-11008
=> Amended item definition reference for CertifiedCopyItem item options

src/services/order/certified-copies/types.ts
Amended ItemOptions for certified documents to have optional properties
BI-11008
=> Amended ItemOptions for certified documents to have optional properties

src/services/order/certified-copies/types.ts
Created a separate type for patch item options
BI-11008
=> Created a separate type for patch item options

src/services/order/order-item/service.ts, test/services/order-item/service.spec.ts, test/stubs/item.stub.ts
* Implement order item client
* New getOrderItem endpoint will return a single item belonging to an
order.
[GCI-2266](https://companieshouse.atlassian.net/browse/GCI-2266)
=> GCI-2266 Order item service

src/services/order/order-item/service.ts, test/services/order-item/service.spec.ts
* Order item error model comprises of a single error field.
=> Change data structure of order item err model

src/services/order/basket/mapping.ts, src/services/order/basket/types.ts, src/services/order/checkout/types.ts, src/services/order/order/types.ts, test/services/basket/mapping.spec.ts, test/services/basket/service.spec.ts, test/services/checkout/service.spec.ts, test/services/order/service.spec.ts
Add an optional company name property to delivery address objects for orders
Resolves: BI-11583
=> Bi 11583 add company name

src/services/order/checkout-item/service.ts, test/services/checkout-item/service.spec.ts
* The `getCheckoutItem` endpoint filters and returns an item in a checkout
resource by item ID.
=> Implement client for getCheckoutItem endpoint

package-lock.json, src/services/overseas-entities/service.ts
https://companieshouse.atlassian.net/browse/ROE-1271
Adding ROE PUT and PATCH functions for a proof of concept.
We are unable to get the SDK branch included in the Docker build so will merge to master to enable us to include the new release of the SDK into the overseas-entity-web proof of concept.
POC functions will be removed after POC finished - https://companieshouse.atlassian.net/browse/ROE-1298
=> ROE-1271 Proof of Concept save and resume

package-lock.json, src/services/order/order/service.ts, test/services/order/service.spec.ts
* Create custom order error response to handle when orders api is down
[GCI-2286](https://companieshouse.atlassian.net/browse/GCI-2286)
=> GCI-2296 Create custom order error response

src/services/order/checkout-item/service.ts, test/services/checkout-item/service.spec.ts, test/stubs/checkout-item.stub.ts
* Changes the getCheckoutItem endpoint to return a checkout with an item embedded
[GCI-2340](https://companieshouse.atlassian.net/browse/GCI-2340)
=> GCI-2340 Embed item within a checkout resource

src/services/overseas-entities/service.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Resolves [ROE-1429](https://companieshouse.atlassian.net/browse/ROE-1429)
Add PUT endpoint call to Update OE
=> Add PUT endpoint call to Update OE

src/services/overseas-entities/service.ts
Part of [ROE-1430](https://companieshouse.atlassian.net/browse/ROE-1430)
Update POST fingerprint for OE to cover temporary Save and Resume endpoint
=> Update post fingerprint for OE

src/services/overseas-entities/types.ts
Update ROE model with second nationality for BOs and MOs Individual
Resolves [ROE-1602](https://companieshouse.atlassian.net/browse/ROE-1602)
=> Update ROE model with second nationality for BOs and MOs Individual

src/services/overseas-entities/mapping.ts, test/services/overseas-entities/overseas.entities.spec.ts
Fix bug on mapIsoDate
Part of [ROE-1539](https://companieshouse.atlassian.net/browse/ROE-1539)
=> Fix bug on mapIsoDate

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Resolves [ROE-1750](https://companieshouse.atlassian.net/browse/ROE-1750)
Add entity name changes
=> Roe feature entity name changes

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
https://companieshouse.atlassian.net/browse/UAR-207 Pass the entity_number through to the overseas-entity-api
tested with dist files from working branch uar-207-oe-number
=> uar-207 entity-number

src/services/file-transfer/types.ts
Fulfils [BI-12506](https://companieshouse.atlassian.net/browse/BI-12506)
[BI-12506]: https://companieshouse.atlassian.net/browse/BI-12506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding model types to represent file data

src/services/company-officers/types.ts, src/services/company-profile/service.ts, src/services/company-profile/types.ts, src/services/company-psc/types.ts, test/services/company-profile/mocks.ts, test/services/company-profile/service.spec.ts
https://companieshouse.atlassian.net/browse/UAR-337 
pass through BO mappings
pass through MO mappings
Add missing registration_number for company_profile (fix in web app under https://companieshouse.atlassian.net/browse/UAR-350)
testing branch for this with dist files: feature/uar-337-bo-mapping-testing
npm install "https://github.com/companieshouse/api-sdk-node.git#feature/uar-337-bo-mapping-testing" --save
=> uar-337 add missing bo mappings

src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
Part of Jira [ROE-2082](https://companieshouse.atlassian.net/browse/ROE-2082)
[ROE-2082]: https://companieshouse.atlassian.net/browse/ROE-2082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add new field is_on_register_in_country_formed_in to trust corporate interfaces

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Jira [UAR-331](https://companieshouse.atlassian.net/browse/UAR-331)
Adding Update model to node to enable Save and Resume Update functionality
[UAR-331]: https://companieshouse.atlassian.net/browse/UAR-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UAR-331: Adding Update object to model

test/services/payment/service.spec.ts
Updates assertion in create payment service test
=> Test: Update assertion in service test

src/http/request-client.ts
Validates response status to only error on 5xx
=> Feature: Validate response status

src/services/company-officers/types.ts, test/services/company-officers/service.spec.ts
JIRA link: https://companieshouse.atlassian.net/browse/UAR-151
Add the self link for officer items. Already passed through but was not in model type.
=> uar-151 add officer self link

src/services/company-officers/types.ts, test/services/company-officers/service.spec.ts
JIRA https://companieshouse.atlassian.net/browse/UAR-151
bug fix - declaration was missed in first PR
=> uar-151 fix missing self link

package-lock.json, src/services/officer-filing/service.ts, src/services/officer-filing/types.ts, test/services/officer-filing/officer.filing.mock.ts
**As** companies house
**I want** Officer ID for the director I'm trying to be removed to be saved
**So that** I am able to use the data on future pages and for validation
[DACT-489](https://companieshouse.atlassian.net/browse/DACT-489)
[DACT-489]: https://companieshouse.atlassian.net/browse/DACT-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DACT-489 Officer filing TM01 post

test/services/payment/service.spec.ts
One unit test failing for payments.
=> fix failing payments test

src/services/officer-filing/service.ts, src/services/officer-filing/types.ts, test/services/officer-filing/officer.filing.mock.ts, test/services/officer-filing/officer.filing.spec.ts
Original Context
The 'When was the Director removed from the company?' page is the 7th page in the happy path journey for the web service. It acts as a page where an Officer may enter a date when the director was removed from a company. An Officer should be able to;
Click the ‘continue’ button to move to the 'Check your answers before submitting the removal of a director' page.
GET validation status endpoint required for user input {DATE} validation
=> Added validation status GET endpoint

src/client.ts, src/enums/ClientType.ts, src/enums/index.ts
Adds client type field to be used to identify the client type in `sdk-manager`
=> Feat: Add client type to client module

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
JIRA link: https://companieshouse.atlassian.net/browse/UAR-587
Add no_change Yes/No statement to the overseas_entity update model
=> uar-587 add no change statement to overseas entity model

package-lock.json, package.json
- Adds override for `semver` dependency in package.json
- Updates package-lock
=> Fix/CC-291: Add override for `semver` dependency

src/services/overseas-entities/service.ts, test/services/overseas-entities/overseas.entities.spec.ts
https://companieshouse.atlassian.net/browse/UAR-616
Add transaction id to getOverseasEntityDetails
=> uar-616 add transaction id to getOverseasEntityDetails

src/services/company-officers/types.ts, test/services/company-officers/service.spec.ts
JIRA https://companieshouse.atlassian.net/browse/UAR-838
Add officer responsibilities as optional field to the typing (already passing through in raw response)
=> uar-838 add officer responsibilities as optional field

src/services/company-officers/types.ts, test/services/company-officers/service.spec.ts
Jira [UAR-913](https://companieshouse.atlassian.net/browse/UAR-913)
Adding contact name of corporate MO so that it can be displayed in web
[UAR-913]: https://companieshouse.atlassian.net/browse/UAR-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UAR-913: Contact name of Corporate MO

src/services/overseas-entities/service.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/UAR-619
Individual MO residential address displayed to the user
=> Individual MO residential address displayed to the user

src/services/overseas-entities/service.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
JIRA 
https://companieshouse.atlassian.net/browse/UAR-619
Return the private bo and mo data as []s
Renamed  getBeneficialOwnersPrivateData ->  getBeneficialOwnerPrivateData
Renamed ManagingOfficerDataResource -> ManagingOfficerPrivateDataResource
=> uar-619 return lists of bo, mo private data

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
https://companieshouse.atlassian.net/browse/UAR-109
Associated changes in web requiring this change:
- https://github.com/companieshouse/overseas-entities-web/pull/1065
Added 'review' meta data to trust model.
=> UAR-109: Added 'review' object to Trusts-in-review model

package-lock.json, package.json
Upgrades to node v18 and tests on v20
=> Feat/CC-878: Upgrade to node v18

package-lock.json, package.json
Test axios breaking change with actual release
=> Test/CC-911: Update to test axios breaking change

src/services/officer-filing/service.ts, src/services/officer-filing/types.ts
https://companieshouse.atlassian.net/browse/DACT-1255
=> Update to JSON Field Names

README.md
Added additional instructions for how to test changes to this repo when included in another project, running locally on a developer machine.
=> Update README file for development

src/services/officer-filing/service.ts, src/services/officer-filing/types.ts
JIRA https://companieshouse.atlassian.net/browse/DACT-1443
Add optional description to officer filing
=> dact-1443 add description field to officer filing

src/services/company-profile/service.ts, src/services/company-profile/types.ts, src/services/officer-filing/service.ts, src/services/officer-filing/types.ts, test/services/officer-filing/officer.filing.mock.ts, test/services/officer-filing/officer.filing.spec.ts
JIRA 
https://companieshouse.atlassian.net/browse/DACT-1816 add dateOfCessation
https://companieshouse.atlassian.net/browse/DACT-2289 remove careOf
=> dact-2289 dact-1816 remove careof add date-of-cessation

src/services/officer-filing/service.ts, src/services/officer-filing/types.ts
JIRA: https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-2180
Flag name change from correspondenceAddressHasBeenUpdated to serviceAddressHasBeenUpdated
=> DACT-2180: Flag changed to serviceAddressHasBeenUpdated

.gitignore, package-lock.json, package.json, src/services/psc-verification-link/service.ts, src/services/psc-verification-link/types.ts, test/services/psc-verification-link/service.mock.ts, test/services/psc-verification-link/service.spec.ts
- make PscVerification properties optional:
- psc_appointment_id
- verification_details
- add nyc  for test coverage reporting
- add 'test:coverage' npm script
=> Add unit tests for psc-verification-link service

test/services/psc/service.mock.ts, test/services/psc/service.spec.ts
=> Fixed indentation

src/services/account-validator/types.ts
Make the data fields from the felix validator response optional.
=> Make felix data optional

src/services/psc-verification-link/service.ts, test/services/psc-verification-link/service.mock.ts, test/services/psc-verification-link/service.spec.ts
=> Add content type header for patch

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1449
* Type fields added to support the new 'still involved' question for a trust
* Mapping code updated to send/receive data to/from the API
* Tests updated
=> UAR-1449 Enable Ceased Dates for trusts when no trustees

src/services/acsp/service.ts, test/services/acsp/acsp.mock.ts, test/services/acsp/acsp.spec.ts
https://companieshouse.atlassian.net/browse/IDVA5-198
Added post endpoint and unit tests
=> Added post request for calling ACSP confirmation email endpoint

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1545
Adding mapping for overseas entities to map the ceased date and still involved indicator for Trust Individuals
=> UAR-1545 Add Overseas Entities mappings for Trust Individual types

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/UAR-1412
add ch_reference field to trust to ensure it is persisted to Mongo
=> uar-1412 add ch_reference field

src/services/overseas-entities/types.ts
https://companieshouse.atlassian.net/browse/UAR-1400
Add missing trust sub-entities ids in MongoDB
=> uar-1400 add ids to trust sub entities

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Saves `who_is_registering` option to the API
=> Feat/ROE-2561: Save `who_is_registering` option to database

src/services/acsp/types.ts
Created a new subdoc called : applicant_details
and moved the following attributes under it.
first_name,
middle_name,
last_name,
date_of_birth,
nationality,
country_of_residence,
correspondence_address,
correspondence_address_is_same_as_registered_office_address.
=> Bring person detail together

src/services/acsp/types.ts
changes for field email and registeredOfficeAddress
=> changes for field email and registeredOfficeAddress

package-lock.json, package.json
JIRA link
https://companieshouse.atlassian.net/browse/ASM-328
upgrade axios - security vulnerability
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
=> asm-328 - upgrade axios - security vulnerability

src/services/acsp/service.ts, test/services/acsp/acsp.spec.ts
updated endpoint urls for acsp
=> updated endpoint urls for acsp

src/services/acsp/service.ts, src/services/acsp/types.ts, test/services/acsp/acsp.mock.ts, test/services/acsp/acsp.spec.ts
Updated acsp-web service to send snake case to acsp-api and convert to camel case for acsp-web
=> Case changes for acsp-api & acsp-web

src/services/account-validator/types.ts
Add company number to account validator request object.
=> Add company number to AccountValidatorRequest

src/services/acsp/types.ts
Added correspondence email to acsp applicant details interfaces
=> Added correspondence email to acsp data types

src/services/acsp/types.ts
Updated ACSP correspondence email to be optional in applicant details
=> updated acsp correspondence email to be optional in applicant details

src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
PR: https://companieshouse.atlassian.net/browse/UAR-1611
Added new nocs to the types
Added new noc type for jurisdictions
Updated the test data
=> UAR-1611 Overseas entities GPA BO new nocs

test/services/overseas-entities/overseas.entities.mock.ts
https://companieshouse.atlassian.net/browse/UAR-1611
* Fixes a lint error that was preventing new builds/releases
=> UAR-1611 Remove trailing commas

src/services/acsp/service.ts, test/services/acsp/acsp.spec.ts
Updating deleteSavedApplication endpoint to use new deleteAcspApplicationAndTransaction service in acsp-api.
=> Updating deleteSavedApplication endpoint

src/services/acsp/types.ts
Adding field acspType to be stored in DB for https://companieshouse.atlassian.net/browse/IDVA5-1433
=> Adding AcspType to AcspData and AcspDataDto types

src/client.ts
JIRA
https://companieshouse.atlassian.net/browse/LP-202
Description
add limited-partnerships service to client
=> lp-202 : add limited-partnerships service to client

sonar-project.properties
Location was pointed at a folder which does not get generated hopefully this resolves it...
=> CC-1673 - Fix coverage location

src/services/limited-partnerships/service.ts, src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-371
add getLimitedPartnership method to limited partnership service
=> lp-371 : add getLimitedPartnership method to limited partnership service

src/services/limited-partnerships/service.ts, src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA: https://companieshouse.atlassian.net/browse/LP-435
Added link to incorporation get endpoint and new model type for the data returned.
5 new unit tests added.
=> LP-435 Limited partnerships incorporation GET endpoint

package-lock.json, package.json, src/services/acsp/service.ts, src/services/acsp/types.ts, test/services/acsp/acsp.mock.ts, test/services/acsp/acsp.spec.ts
Adding endpoint for sending ACSP verify a client email confirmation
=> Adding endpoint for sending ACSP verify a client email confirmation

src/services/acsp/service.ts
updating sendIdentityVerificationEmail endpoint url
=> updating sendIdentityVerificationEmail endpoint url

src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
https://companieshouse.atlassian.net/browse/LP-387
Add the registered_office_address to LimitedPartnership type
=> LP-387 Add registered office address to limited partnership

src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-234
add term to LimitedPartnership
=> lp-234 : add term to LimitedPartnership

src/services/overseas-entities/service.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
- Adds force flag to PUT url (usually required for post-transaction updates)
- Adds force flag to GET url (usually required for post-payment fetches)
=> feat/roe-2732: add force flag to PUT and GET requests

src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts
https://companieshouse.atlassian.net/browse/LP-400
Add principal place of business address to the sdk.
=> LP-400 limited partnerships - principal place of business

src/services/acsp/types.ts
Adding acspId to AcspData model
=> Adding acspId to AcspData model

src/services/overseas-entities/service.ts
Debugging force flag in the flow
=> Debugging force flag in the flow- PLEASE REVERT AFTER TESTING

src/services/overseas-entities/service.ts
Differentiates between PUT and GET debuggers for overseas entity service
=> debug: differentiate between PUT and GET debuggers for overseas entity service

src/services/limited-partnerships/service.ts, src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-537
Added support for general partner person data
Work checklist
Tests added where applicable
UI changes look good on mobile
UI changes meet accessibility criteria
Merge instructions
We are committed to keeping commit history clean, consistent and linear. To achieve this commit should be structured as follows:
<type>[optional scope]: <description>
and contain the following structural elements:
fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic versioning),
feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic versioning),
BREAKING CHANGE: a commit that has a footer BREAKING CHANGE: introduces a breaking API change (correlating …
=> Lp 537 support general partner person data

src/services/limited-partnerships/service.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-550
add getGeneralPartner method to limited partnership service
=> lp550-create general partner usual residential  choice page

src/services/limited-partnerships/service.ts, src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
https://companieshouse.atlassian.net/browse/LP-617
* New Incorporation structure defined with 'kind' field
* enum added for 'kind' - covers registration and transition
* POST end-point call changed
* Test updated
=> LP-617 Changes to support 'kind' field when creating LP incorporations

src/services/limited-partnerships/service.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-595
LimitedPartnershipService - patchGeneralPartner
=> lp-595 : LimitedPartnershipService - patchGeneralPartner

src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-223
limited-partnerships service - add sic_codes
=> lp-223 : limited-partnerships service - add sic_codes

package-lock.json, src/services/acsp/types.ts
https://companieshouse.atlassian.net/browse/IDVA5-1849
As part of Update ACSP, we are capturing dateOfChange for Add AML and Remove AML. To handle logic I'm adding optional dateOfChange to AmlSupervisoryBody in types. 
Storing as string as we convert the Date to ISOString to handle pre-1960 dates.
=> dateOfChange added to AmlSupervisoryBody model

tsconfig.json
Remove test directory from TypeScript include paths
=> Fix compiled files not being generated in /dist

src/services/limited-partnerships/service.ts, src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-237
limited-partnership service - add getGeneralPartners
=> lp-237 : limited-partnership service

src/services/limited-partnerships/service.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-686
limited partnerships service - delete general partner
=> lp-686 : limited partnerships service - delete general partner

src/services/limited-partnerships/service.ts, src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-648
Abstracted common fields for GP and limitedPartner fields
new interface for LimitedPartner
service functions for get, patch, delete, post limitedPartner
mocks + tests
Work checklist
Tests added where applicable
UI changes look good on mobile
UI changes meet accessibility criteria
Merge instructions
We are committed to keeping commit history clean, consistent and linear. To achieve this commit should be structured as follows:
<type>[optional scope]: <description>
and contain the following structural elements:
fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic versioning),
feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic …
=> LP-648 limited partner sdk changes

src/services/acsp/service.ts
Ticket [IDVA5-2230](https://companieshouse.atlassian.net/browse/IDVA5-2230)
[IDVA5-2230]: https://companieshouse.atlassian.net/browse/IDVA5-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reverting logger changes

src/client.ts, src/services/associations/index.ts, src/services/associations/service.ts, src/services/associations/types.ts, test/services/associations/service.mock.ts, test/services/associations/service.spec.ts
Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-450
Changes:
- Associations service added
=> SIV-450 create association service

src/services/associations/service.ts, test/services/associations/service.spec.ts
Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-461
Changes:
- Optional parameter removed from getCompanyAssociations function
- A new POST endpoint function added
=> SIV-461 amendments for associations companies company number

src/services/associations/service.ts
Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-528
Changes:
- Import statement fixed
- Unused imported interface removed
=> SIV-528 Import statement fixed

package-lock.json
=> chore/cc-2938: fix axios vulnerability

src/services/confirmation-statement/service.ts, src/services/confirmation-statement/types.ts
Ticket:
https://companieshouse.atlassian.net/browse/CSE-680
Changes:
- add new field `new_confirmation_date` to ConfirmationStatementSubmissionDataResource and ConfirmationStatementSubmissionData
- update the mapping method for the new field `new_confirmation_date`
=> CSE-680: ACSP - Confirmation Statement Date - Transaction Update

package-lock.json, package.json, src/services/confirmation-statement/service.ts, src/services/confirmation-statement/types.ts, test/services/confirmation-statement/confirmation.statement.mock.ts, test/services/confirmation-statement/confirmation.statement.spec.ts
Update to data model to take SicCode Array and validate updated SicCode values.
=> Cse 681 sic code transaction

src/services/limited-partnerships/types.ts
JIRA link
https://companieshouse.atlassian.net/browse/LP-1269
limited partnership - add new kinds in PartnerKind
=> lp-1269 : add new kinds in PartnerKind
