companieshouse/api-sdk-node

src/client.ts, src/services/refresh-token/index.ts, src/services/refresh-token/service.ts, src/services/refresh-token/types.ts, test/services/refresh-token/service.spec.ts
JIRA: https://companieshouse.atlassian.net/browse/SR-129
Added a new `RefreshTokenService` on the Account domain using the `accountClient`, which supports refreshing user session access tokens for API requests.
=> feat: add refresh access token service

src/services/search/dissolved-search/service.ts, test/services/search/dissolved-search/service.spec.ts
Add searchType parameter to getCompanies function in dissolved search service to  be used to determine correct api end point to query.
Resolves: BI-7129
=> Add logic to getCompanies to determine correct end point to query

src/client.ts
Fix issue where services using api-sdk-node cannot find the psc discrepancy service.
=> Fix import causing build failure when building apps that use sdk

src/services/search/dissolved-search/service.ts, src/services/search/dissolved-search/types.ts, test/services/search/dissolved-search/service.spec.ts
Update dissolved search alphabetical to handle search before, search after and size query params to create the url being passed to the api.
Updated model ordered alphakey with id
Update test
Resolves: BI-7008
=> add query params for dissolved search alphabetical update tests

src/services/company-profile/types.ts
revision to ncs-89 -> https://github.com/companieshouse/api-sdk-node/commit/1802774c2d6e199b25580ca49f03c82e8ef4e3cd
updating nextMadeUpTo to be non-optional as described in spec -> https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companyprofile?v=latest
=> make nextMadeUpTo in confirmationStatement non optional

src/services/search/dissolved-search/types.ts, test/services/search/dissolved-search/service.spec.ts
Added in the matched_previous_name type, added it to items and the top_hit as well as amended the tests
Resolves: BI-8365
=> BI-8365: Update SDK to include matched_previous_names

src/services/transaction/service.ts, test/services/transaction/service.spec.ts
The transaction putTransaction api call doesn't return a body so it was crashing when trying to map the body in the response. Removed the call to map the body in the response.
=> NCS-642 Put Transaction fix to remove response mapping

src/services/confirmation-statement/service.ts, src/services/confirmation-statement/types.ts, test/services/confirmation-statement/confirmation.statement.mock.ts, test/services/confirmation-statement/confirmation.statement.spec.ts
adding the made up to date to the ConfirmationSubmission types and including it in the mapping of data between api resource and type.
=> NCS-681 Add made up to date to Confirmation Statement types and mapping

src/services/confirmation-statement/service.ts, src/services/confirmation-statement/types.ts, test/services/confirmation-statement/confirmation.statement.mock.ts, test/services/confirmation-statement/confirmation.statement.spec.ts
Making data block mandatory as it should be populated with a made up to date when confirmation statement record is created.
=> NCS-681 Making confirmation statement data mandatory

src/services/confirmation-statement/service.ts, src/services/confirmation-statement/types.ts, test/services/confirmation-statement/confirmation.statement.mock.ts
Add corporate identifier fields to ActiveOfficerDetails.
PS: ticket has been renamed NCS-828 -> [BI-9482](https://companieshouse.atlassian.net/browse/BI-9482).
=> NCS-828 Add officerType to ActiveOfficerDetails object

src/services/order/certificates/mapping.ts, src/services/order/certificates/types.ts, src/services/order/order/mapping.ts, src/services/order/order/types.ts, test/services/certificates/service.spec.ts, test/services/order/service.spec.ts
- Add liquidators details types and mappings
- Fix Typescript warnings
- Remove unused imports and types
Resolves: [Add liquidators_details field: api-sdk-node](https://companieshouse.atlassian.net/browse/BI-9543)
=> BI-9543 Add liquidators details types and mappings

src/services/order/checkout/mapping.ts, src/services/order/checkout/types.ts, src/services/order/order/mapping.ts, src/services/order/order/types.ts, test/services/checkout/service.spec.ts
* Add missed liquidators details fields to checkout types and mapping
* Add missed liquidators details fields to order types and mapping
* Re-instate removed DirectorOrSecretaryDetails interface (required by orders.web.ch.gov.uk)
Resolves: [Upgrade api-sdk-node version: orders.web.ch.gov.uk](https://companieshouse.atlassian.net/browse/BI-9545)
=> Add liquidators details fields

Makefile, src/services/order/certificates/service.ts, test/services/certificates/service.spec.ts
* Standardise on ApiResponse as the response object from both initial and create
requests
Relates to: [Refactor company status and info into an enrichment](https://companieshouse.atlassian.net/browse/BI-9889)
=> BI-9889 Unify create and certificate initial and post response

src/services/order/certificates/service.ts, test/services/certificates/service.spec.ts
* Handler methods for read and update certified certificates now use
result API.
Related:
[BI-10662](https://companieshouse.atlassian.net/browse/BI-10662)
=> BI-10662 Rework read/update certs handlers - errors

src/services/search/advanced-search/service.ts, src/services/search/advanced-search/types.ts, test/services/search/advanced-search/service.spec.ts
Allow search api to be called from the web with a company_subtype query param values via sdk
Resolves: BI-10797
=> add company subtype to advanced search query params update test

src/services/order/search/types.ts, test/services/order/search.spec.ts
* The page_size query parameter controls how many results will be
returned per page by the orders search endpoint.
=> GCI-2073 Support page_size param in orders search endpoint

src/services/overseas-entities/mapping.ts, test/services/overseas-entities/overseas.entities.spec.ts
Related to [ROE-849](https://companieshouse.atlassian.net/browse/ROE-849)
Remove identity date field for OE due diligence when blank
=> Remove identity date field for OE due diligence when blank

src/services/overseas-entities/mapping.ts, test/services/overseas-entities/overseas.entities.spec.ts
* Send null instead of {} if due didligence object is empty
* Ensures object field not written by API to Mongo and fixes
an issue in chips-filing-consumer
=> ROE-849 Send nulls for empty due diligence objects

src/services/order/certificates/types.ts, src/services/order/certified-copies/types.ts, src/services/order/checkout/types.ts, src/services/order/types.ts
* Checkout paidAt, paymentReference fields may be undefined if checkout
resource hasn't been updated by payment-processed-consumer.
* Segregate deliveryTimescale field in ItemOptions x3 into standalone
interface.
=> GCI-2149 Checkout model updates

src/services/order/checkout-item/service.ts, test/services/checkout-item/service.spec.ts
* Adds condition which checks for items to exists on the response body before checking its length
=> Add condition to catch when items array undefined

src/services/overseas-entities/mapping.ts, test/services/overseas-entities/overseas.entities.spec.ts
Part of [ROE-1677](https://companieshouse.atlassian.net/browse/ROE-1677)
Return null object for the `presenter` and `entity` when they are empty
=> Return null object when presenter and entity are empty

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Added a feature branch
Added the Entity_Name
Removed the name field from the exiting entity block
Assumed we want to add the feature branch everywhere and if we are changing existing code then we'll need it.
=> Roe 1750 add entity name model

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
https://companieshouse.atlassian.net/browse/ROE-1945 
Updated resource model to mirror the new block in the api.
Map single field to the block when mapping to the resource for POST and vice versa when using GET.
=> Roe 1945 - TL - entity name mapping post and get

src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
Jira [ROE-1918](https://companieshouse.atlassian.net/browse/ROE-1918)
Add extra fields for Historic Beneficial Owner (and related test class) to use this for both former individual and former legal entity trustee types
[ROE-1918]: https://companieshouse.atlassian.net/browse/ROE-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ROE-1918: Add extra new corporate BO fields to types and tests

src/services/psc-discrepancies-report/service.ts, src/services/psc-discrepancies-report/types.ts, test/services/psc-discrepancies-report/service.spec.ts, test/services/psc-discrepancies-report/util.spec.ts
Resolves [BI-12586](https://companieshouse.atlassian.net/browse/BI-12586)
- Add material discrepancies into the type definition
- Update call to create report to use material discrepancies
[BI-12586]: https://companieshouse.atlassian.net/browse/BI-12586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-12586 Add Material Discrepancies to PSC Discrepancies Report

src/client.ts, src/services/officer-filing/index.ts, src/services/officer-filing/service.ts, src/services/officer-filing/types.ts, test/services/officer-filing/officer.filing.mock.ts, test/services/officer-filing/officer.filing.spec.ts
The current directors page is the 6th page in the happy path journey for the web service. It acts as a page where an Officer may select from a list of active directors associated with a company to remove.
An Officer should be able to click the remove director link which will take them to the ‘When was this director removed ?’ (removal date) page.
To complete this work, we first need an endpoint to retrieve the list of active Directors.
=> DACT-385-list-of-active-directors

src/http/request-client.ts
- Standardises `axios` integration options to include explicit header fields
- Removes status validator so as to implicitly use status in response
=> Chore: Standardise axios integration options

src/http/request-client.ts, test/http/request-client.spec.ts
Checks the `uri` passed in for a leading slash and adds it in if it's missing.
=> Fix: Check incoming uri for missing leading slash

src/http/request-client.ts, test/http/request-client.spec.ts
- Returns a fully qualified url without a trailing slash
- Extends tests to account for additional logic
=> Fix: Return fully qualified url without trailing slash

src/services/officer-filing/service.ts, test/services/officer-filing/officer.filing.mock.ts, test/services/officer-filing/officer.filing.spec.ts
Officer Filing - Logic to enable dissolved company stop screen 
[DACT-410] (https://companieshouse.atlassian.net/browse/DACT-410):
- Added officer-filing-api getCurrentOrFutureDissolved method call
[DACT-410]: https://companieshouse.atlassian.net/browse/DACT-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DACT-410: Dissolved stop screen

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/service.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
https://companieshouse.atlassian.net/browse/UAR-616
- Added `getOverseasEntityDetails` endpoint to OE service to retrieve private OE details
- https://github.com/companieshouse/overseas-entities-web/pull/916
- https://github.com/companieshouse/overseas-entities-api/pull/277
=> UAR-616: Retrieve private OE details

src/services/overseas-entities/service.ts, test/services/overseas-entities/overseas.entities.spec.ts
JIRA https://companieshouse.atlassian.net/browse/UAR-616
change getOverseasEntityData signature to take overseas_entity_id instead of oe number
=> uar-616 use overseas entity id in getOverseasEntityData signature

src/services/company-psc/types.ts, test/services/company-psc/service.spec.ts
JIRA 
https://companieshouse.atlassian.net/browse/UAR-998
Middle name is defined for PSCs but not included in the Typescript types.
Example from api:
nameElements: { forename: 'Dr', middleName: 'Lane', surname: 'Foster' }
The CHS dev documentation has: title and fore_names (and no middlename)
The Java API SDK has all of:
title
forename
otherFornames
middleName
surname
aligning with Java API SDK to add all these.
=> uar-998 add middleName to PSC nameElements

package-lock.json, package.json, src/http/request-client.ts, test/http/request-client.spec.ts, test/services/certificates/service.spec.ts
* This work undoes a change made back in April that was recently found to result in the SDK not propagating additional headers provided to its outgoing HTTP requests, as described in [the bug](https://companieshouse.atlassian.net/browse/CC-605).
* It also provides a couple of automated tests that hopefully should catch such issues should they arise again.
* The substantive change was tested with the `certificates.orders.web.ch.gov.uk` node application [manually in Tilt](https://companieshouse.atlassian.net/browse/CC-605?focusedCommentId=220161) earlier today.
=> CC-605: Do not drop additional headers

src/services/officer-filing/types.ts
Context
Currently we send the Post from the load of the date removal screen. Ideally we would run this from the click of the remove a director link on the list of active directors screen.
However, we have found a technical constraint for TM01 that is caused by the link to remove a director on the current directors' page. A button would be the preferred way for handling posts going forward.
Why do we need to resolve this issue asap?
The issue is that Links cannot be used to run a POST request without using javascript to do the submit of the post - Buttons on pages can be used to run a POST request.
We need to run a POST request as we are setting up the filing for that individual director when you click on the remove director link on the current directors' page.
We currently do a POST on …
=> DACT-634-Move-Post-Request

src/services/lfp/service.ts, test/services/lfp/service.spec.ts
This pr changes the penalties sdk so that when the lfp-pay-api returns null for company penalty items, the service takes that as there being no penalties and a blank array is used. This is to fix an issue seen in the lfp-appeals-frontend when a company with no penalities is used.
=> Add null check to penalty list items

src/index.ts
Adds comment annotation discouraging direct use of the `createApiClient` method in favour of `sdk-manager-node`
=> Chore/CC-142: Add comment annotation to discourage direct use of method

src/services/confirmation-statement/service.ts, src/services/confirmation-statement/types.ts, test/services/confirmation-statement/confirmation.statement.mock.ts, test/services/confirmation-statement/confirmation.statement.spec.ts
https://companieshouse.atlassian.net/browse/ECCT-719
New functionality in CHS Confirmation Statement service to confirm the email address for the first time. Cross web service call from confirmation-statement-web service to ConfirmationStatementSubmission and update the section status for registered_email_address_data.
New section status of 'INITIAL_FILING'.
=> confirmation-statement-web service call changes reqd for confirm registered email address

src/services/officer-filing/service.ts, test/services/officer-filing/officer.filing.spec.ts
JIRA https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-1816
Remove getCurrentOrFutureDissolved from SDK as web can use companyProfile directly instead.
=> dact-1816 remove getCurrentOrFututureDissolved from officer filling

src/services/officer-filing/service.ts, test/services/officer-filing/officer.filing.mock.ts, test/services/officer-filing/officer.filing.spec.ts
JIRA https://companieshouse.atlassian.net/browse/DACT-2515
Web logs were showing a null reference failure to map response so added explicit check for status before mapping.
Noticed no tests on POST or PATCH officer filing so added some.
=> dact-2515 test for status to skip mapping response

src/client.ts, src/config.ts, src/services/account-validator/types.ts, src/services/accounts-filing/index.ts, src/services/accounts-filing/service.ts, src/services/accounts-filing/types.ts, src/services/transaction/service.ts, src/util.ts, test/services/accounts-filing/service.spec.ts
As part of moving the `accounts-filing-api` from the internal API to the external API, the `accounts-filing` service is moved from the `private-api-sdk-node` to the `api-sdk-node`.
Once this PR has been mereged and released, the `accounts-filing` service will be removed from the `private-api-sdk-node`.
The `accounts-filing` types relied on type from the `account-validator` service which is in the private sdk. Since the public SDK cannot access the private one, these types have been moved too and services which use the account validator node sdk will have to updated to refer to the types from the api-sdk-node instead.
Additionally, this PR adds the ability to set the requestID header for the accounts-filing service as well as the transactions service. This will aid
=> Move accounts filing to public sdk

src/services/overseas-entities/types.ts
https://companieshouse.atlassian.net/browse/UAR-1402
Ids were not being saved to Mongo when BOs and MOs moved out of review on an Update/Remove journey. This then caused various issues if the submission was saved and later resumed. Ids are now sent to - and persisted by - the OE API, allowing things to work as expected.
=> UAR-1402 Update save and resume ids for BOs and MOs

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Adds has_sold_land key to the api-sdk so it can be saved and retrieved from the database
JIRA ticket:
https://companieshouse.atlassian.net/browse/ROE-2559
=> Feat/ROE-2559: Add `has_sold_land` key to api-sdk

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Adds `is_secure_register` key to data mappers in the sdk
=> Feat/ROE-2560: Add `is_secure_register` key to data mappers

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts
Jira Ticket:  https://companieshouse.atlassian.net/browse/ROECCT-245
This involves adding a new field to the legal beneficiary page to allow users to input the date they became a beneficiary. This includes updating the UI to include the new field, validating the input, and ensuring the data is saved correctly in the backend.
=> ROECCT-245 - Add New field for legal entity beneficiaries to indicate became dates.

src/services/overseas-entities/mapping.ts
Straightens out the sdk resource mapping discrepancy for the boolean fields: `has_sold_land` and `is_secure_register`.
=> Fix/ROE-2636: Straighten out resource mapping discrepancy for boolean fields

Makefile
Should allow coverage to be displayed properly for Sonar checks.
=> CC-1673 - Generate coverage when running sonar checks

src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
https://companieshouse.atlassian.net/browse/LP-312
Added the new enum and introduced it as a new data field "partnership_type" in the LimitedPartnership interface.
Added a comment about this here:
https://companieshouse.atlassian.net/wiki/spaces/Arch/pages/4925817463/LP+Data+Model+-+Company+Details
=> LP-312: Limited Partnership Type Enum

src/services/limited-partnerships/service.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
https://companieshouse.atlassian.net/browse/LP-367
Updated patch function body parameter to no longer use the the data key value buckets.
=> LP-367 Limited partnerships - Update PATCH function data parameter

src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts, test/services/limited-partnerships/limited.partnerships.spec.ts
https://companieshouse.atlassian.net/browse/LP-450
Added jurisdiction field to the lp sdk model and to the test mocks.
=> LP-450 Intro limited partnerships jurisdiction field

src/services/overseas-entities/mapping.ts, src/services/overseas-entities/types.ts, test/services/overseas-entities/overseas.entities.mock.ts, test/services/overseas-entities/overseas.entities.spec.ts
Adds payment metadata to overseas entity object
=> feat/roe-2732: add payment metadata to overseas entity object

package-lock.json
axios Requests Vulnerable To Possible SSRF and Credential Leakage via Absolute URL - https://github.com/advisories/GHSA-jr5f-v2jv-69x6
=> Fix security vulnerability with Axios

src/services/limited-partnerships/types.ts, test/services/limited-partnerships/limited.partnerships.mock.ts
https://companieshouse.atlassian.net/browse/LP-789
* Add missing field definition for a Limited Partner Legal Entity
* Update the test mock
=> LP-789 Ensure LP Legal Entity statement check saved to Mongo
